stages:
  - test
  
  - build

test:
  stage: test
  image: golang:1.17
  script: 
   - go test .
  rules:
    - changes:
      
      - ".go"
      when: always
    - when: never  
      



build:
  stage: build
  image: docker:latest
  script:
   - docker build .
